### ISSUE TITLE
app crashes receiving a notification during startup

### ISSUE THREAD

**Issue by levepic** [wix/react-native-notifications#1014]
Getting multiple crash reports since the app went live. I suspect the app crashes when receives a notification during startup. The error is the following:

`Fatal Exception: java.lang.IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
       at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:158)
       at com.wix.reactnativenotifications.core.JsIOHelper.sendEventToJS(JsIOHelper.java:21)
       at com.wix.reactnativenotifications.core.JsIOHelper.sendEventToJS(JsIOHelper.java:13)
       at com.wix.reactnativenotifications.core.notification.PushNotification.notifyReceivedBackgroundToJS(PushNotification.java:214)
       at com.wix.reactnativenotifications.core.notification.PushNotification.onReceived(PushNotification.java:69)
       at com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService.onMessageReceived(FcmInstanceIdListenerService.java:28)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:235)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:185)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:172)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:161)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$com-google-firebase-messaging-EnhancedIntentService(EnhancedIntentService.java:78)
       at com.google.firebase.messaging.EnhancedIntentService$$ExternalSyntheticLambda1.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.2.0:2)
       at java.lang.Thread.run(Thread.java:919)`

Versions:

 "react-native": "^0.70.8",
"react-native-notifications": "^5.1.0",

This seems to be similar or the same issue:
https://github.com/OneSignal/react-native-onesignal/issues/877

There is also a solution on the above link provided by [abdullahizzuddiin](https://github.com/abdullahizzuddiin)

**Comment by EnricoMazzu** [comment]
i've found the fix. I will submit a PR

**Comment by EnricoMazzu** [comment]
submited:
https://github.com/wix/react-native-notifications/pull/1050

**Comment by levepic** [comment]
Would be good if your fork could be installed as-is (the dist folder is missing)
