### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by levepic** [wix/react-native-notifications#1054]
This is still an issue:

Fatal Exception: java.lang.IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
       at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:148)
       at com.wix.reactnativenotifications.core.JsIOHelper.sendEventToJS(JsIOHelper.java:21)
       at com.wix.reactnativenotifications.core.JsIOHelper.sendEventToJS(JsIOHelper.java:13)
       at com.wix.reactnativenotifications.core.notification.PushNotification.notifyReceivedBackgroundToJS(PushNotification.java:208)
       at com.wix.reactnativenotifications.core.notification.PushNotification.onReceived(PushNotification.java:68)
       at com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService.onMessageReceived(FcmInstanceIdListenerService.java:28)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.1.0:13)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.1.0:8)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.1.0:3)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.1.0:3)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@21.1.0:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.3.0:6)
       at java.lang.Thread.run(Thread.java:764)

**Comment by EnricoMazzu** [comment]
@levepic : duplicate of https://github.com/wix/react-native-notifications/issues/1014

I've already submitted a pull request

It seems that the author has been inactive for a long time
