### ISSUE TITLE
Is GCM necessary for Android localNotifications?

### ISSUE THREAD

**Issue by shenst1** [wix/react-native-notifications#113]
The docs are written ambiguously. It says I need to set up GCM only if I need to _receive_ a notification. However, you are still technically receiving a notification. If I don't need to receive it, the docs should read differently: "receive a remote notification." If that is not the case and I do need it for a local notification, they should clarify that point: "for receiving any notification, including local". 

The reason I ask is because my android app is crashing silently whenever I try and send a localNotification. Have not set up GCM.

**Comment by shenst1** [comment]
GCM is not necessary for localNotifications. Crashing is being caused by something else.

**Comment by ntomallen** [comment]
@shenst1 how did you fix it? Also getting a crash which shows the following stack trace. Reading it, it seems as if it's trying to get the GCM token, even though I only have a local notification configured.

```
FATAL EXCEPTION: IntentService[GcmInstanceIdRefreshHandlerService]
Process: com.zonderstudios.zonder, PID: 17836
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
    at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:88)
    at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77)
    at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66)
    at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/com.zonderstudios.zonder-1/base.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.zonderstudios.zonder-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.zonderstudios.zonder-1/lib/arm, /system/fake-libs, /data/app/com.zonderstudios.zonder-1/base.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.zonderstudios.zonder-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:88) 
    at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77) 
    at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66) 
    at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23) 
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:154) 
    at android.os.HandlerThread.run(HandlerThread.java:61) ```
