### ISSUE TITLE
android getting token fails

### ISSUE THREAD

**Issue by AndreyNikiforov** [wix/react-native-notifications#141]
Hello,

Following instructions I got iOS working. Now trying to setup Android. After following instructions, my app starts, but log shows:

> D/ReactNativeNotifs: GCM is refreshing token... instanceId=REMOVED
> E/ReactNativeNotifs: Failed to retrieve new token
                                                                                java.lang.Exception: FATAL: Failed to fetch a fresh new token, instanceId=REMOVED
                                                                                    at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:99)
                                                                                    at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77)
                                                                                    at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66)
                                                                                    at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23)
                                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                 Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
                                                                                    at com.google.android.gms.iid.zze.zzb(Unknown Source)
                                                                                    at com.google.android.gms.iid.zze.zza(Unknown Source)
                                                                                    at com.google.android.gms.iid.InstanceID.zzc(Unknown Source)
                                                                                    at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
                                                                                    at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
                                                                                    at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:95)
                                                                                    at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77) 
                                                                                    at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66) 
                                                                                    at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23) 
                                                                                    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:158) 
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)

Can anybody suggest where to look for missing setup or any other troubleshooting steps?

Thanks

PS RN 0.34.1, device, not emulator

**Comment by Noitidart** [comment]
What does your AndroidManifest look like?

**Comment by jussirantala** [comment]
Getting the same error. AndroidManifest:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.mycompany.myapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="24" />

    <application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:debuggable="true"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
`

**Comment by kyunghoon** [comment]
getting same issue, any ideas?

**Comment by minhphung210** [comment]
same issues . Has anyone found a solution yet?

**Comment by skhizerabass** [comment]
I am getting this issue


> ```
> E/ReactNativeNotifs: Failed to retrieve new token
>     java.lang.Exception: FATAL: Failed to fetch a fresh new token, instanceId=diD-y974yV8
>         at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:99)
>         at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77)
>         at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66)
>         at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23)
>         at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:148)
>         at android.os.HandlerThread.run(HandlerThread.java:61)
>      Caused by: java.io.IOException: INVALID_SENDER
>         at com.google.android.gms.iid.zzaf.zzi(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.zze(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
>         at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
>         at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:95)
> ```
