### ISSUE TITLE
App crashes on Android without rendering

### ISSUE THREAD

**Issue by realKfiros** [wix/react-native-notifications#234]
After I installed the module and tried to run my project on Android it didn't even render and crashed.
Here's the log from the logcat:
```
06-25 06:19:08.957  2799  2843 E AndroidRuntime: FATAL EXCEPTION: IntentService[GcmInstanceIdRefreshHandlerService]
06-25 06:19:08.957  2799  2843 E AndroidRuntime: Process: com.wakeamp, PID: 2799
06-25 06:19:08.957  2799  2843 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/util/zzw;
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.zzeK(Unknown Source)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.google.android.gms.iid.zzd.<init>(Unknown Source)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.wix.reactnativenotifications.gcm.GcmToken.getNewToken(GcmToken.java:88)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.wix.reactnativenotifications.gcm.GcmToken.refreshToken(GcmToken.java:77)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.wix.reactnativenotifications.gcm.GcmToken.onAppReady(GcmToken.java:66)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at com.wix.reactnativenotifications.gcm.GcmInstanceIdRefreshHandlerService.onHandleIntent(GcmInstanceIdRefreshHandlerService.java:23)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.util.zzw" on path: DexPathList[[zip file "/data/app/com.wakeamp-2/base.apk"],nativeLibraryDirectories=[/data/app/com.wakeamp-2/lib/x86, /system/fake-libs, /data/app/com.wakeamp-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-25 06:19:08.957  2799  2843 E AndroidRuntime: 	... 13 more
```
My project runs perfectly with this library on iOS.

**Comment by janflei** [comment]
i have the same problem

**Comment by minhphung210** [comment]
same issues

**Comment by andresouza** [comment]
why is this closed? did you find a solution?

**Comment by ardalahmet** [comment]
Upgrading `play-services-gcm` version from `10.0.1` to `15.0.1` fixed the issue for me.

https://github.com/wix/react-native-notifications/blob/2c71cd91925474bd57df174f2e57e0788456697f/android/build.gradle#L23

**Comment by kaushikparmar** [comment]
This is not working for me.
