### ISSUE TITLE
startService issue on Oreo

### ISSUE THREAD

**Issue by Lastin** [wix/react-native-notifications#250]
[GcmInstanceIdListenerService](https://github.com/wix/react-native-notifications/blob/c8594ba1f8edcbba5d76d6626c069a37c345c904/android/src/main/java/com/wix/reactnativenotifications/gcm/GcmInstanceIdListenerService.java) and [RNNotificationsModule](https://github.com/wix/react-native-notifications/blob/7f1845d0425fa137056d84bebce7bc7fb2b22e5d/android/src/main/java/com/wix/reactnativenotifications/RNNotificationsModule.java) use `startService` method, but according to [this](https://developer.android.com/about/versions/oreo/android-8.0-changes#back-all) it has to be replaced with `startForegroundService` and `startForeground`

After upgrading target SDK I have started getting crashes after notification is received if app is in background or closed state.

Any ideas for solution for this?

Error:
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.android.gms.gcm.GcmReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=com.package cmp=com.package/com.wix.reactnativenotifications.gcm.GcmMessageHandlerService (has extras) }: app is in background uid UidRecord{0000000 00000 RCVR idle change:idle|uncached procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Lastin** [comment]
I tried replacing startService with mentioned methods, but that didn't solve it.
However upgrading `com.google.android.gms:play-services-gcm` from _10.0.2_ to _11.2.2_ in my app's `app/build.gradle` did solve the issue.
