### ISSUE TITLE
__DEV__ is not defined

### ISSUE THREAD

**Issue by oriharel** [wix/react-native-notifications#3]
I get __DEV__ is not defined when trying to build for iOS. 
Here's the full exception:

```
> > ReferenceError: __DEV__ is not defined
> >     at Object.<anonymous> (/Users/oriharel/oriApp/NiyoRadar/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
> >     at Module._compile (module.js:398:26)
> >     at Object.Module._extensions..js (module.js:405:10)
> >     at Module.load (module.js:344:32)
> >     at Function.Module._load (module.js:301:12)
> >     at Module.require (module.js:354:17)
> >     at require (internal/module.js:12:17)
> >     at /Users/oriharel/oriApp/NiyoRadar/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:15
> >     at Array.map (native)
> > TransformError: /Users/oriharel/oriApp/NiyoRadar/node_modules/react-native-notifications/index.ios.js: __DEV__ is not defined
> transformed 802/803 (100%)[node-haste] Encountered an error while persisting cache:
> > ReferenceError: __DEV__ is not defined
> >     at Object.<anonymous> (/Users/oriharel/oriApp/NiyoRadar/node_modules/react-native/Libraries/react-native/react-native.js:15:5)
> >     at Module._compile (module.js:398:26)
> >     at Object.Module._extensions..js (module.js:405:10)
> >     at Module.load (module.js:344:32)
> >     at Function.Module._load (module.js:301:12)
> >     at Module.require (module.js:354:17)
> >     at require (internal/module.js:12:17)
> >     at /Users/oriharel/oriApp/NiyoRadar/node_modules/react-native/node_modules/babel-core/lib/transformation/file/options/option-manager.js:284:15
> >     at Array.map (native)
> > TransformError: /Users/oriharel/oriApp/NiyoRadar/node_modules/react-native-notifications/index.ios.js: __DEV__ is not defined
```

I use .babelrc file which has:

```
{
  'presets': ['react-native-stage-0'],
  'plugins': ['transform-decorators-legacy']
}
```

I need it because I use MobX and it has decorators.

[Update] - it also happens even without MobX.

**Comment by oriharel** [comment]
I've just react-native init a fresh new project, npm install react-native-notifications, added:

`import NotificationsIOS from 'react-native-notifications';`
(and only this)
and I got this exception again.
help please...

**Comment by oriharel** [comment]
solved. when using react-native 0.32 and up, added

"babel-preset-react-native": "^1.9.0"
(not stage-0)

and 
"babel": {
    "presets": [
      "react-native"
    ]
  } 
to package.json

**Comment by lidanh** [comment]
Cool!

Sorry for the late response, was on vacation. glad to hear that you solved it!
