### ISSUE TITLE
Android build failing due to minSdkVersion error

### ISSUE THREAD

**Issue by Miraj98** [wix/react-native-notifications#372]
I correctly installed and linked the react-native-notifications library in my project. I am however getting an error that is saying `Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:reactnativenotifications] /Users/... as the library might be using APIs not available in 16`

I am using the latest version of the library and yet I am facing this issue. Any help is much appreciated. I have verified inside `/node_modules/react-native-notifications/android/app/build.gradle` that the `minSdkVersion` is 19. This is a snippet from the file:

```
android {
    compileSdkVersion 27
    buildToolsVersion '28.0.3'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```
 Here is the complete error log: 
```
> Task :app:processDebugManifest FAILED

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
120 actionable tasks: 5 executed, 115 up-to-date
/Users/miraj/assist-versions/Assist/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:reactnativenotifications] /Users/miraj/assist-versions/Assist/node_modules/react-native-notifications/android/app/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.wix.reactnativenotifications" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:reactnativenotifications] /Users/miraj/assist-versions/Assist/node_modules/react-native-notifications/android/app/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.wix.reactnativenotifications" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/miraj/assist-versions/Assist/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:reactnativenotifications] /Users/miraj/assist-versions/Assist/node_modules/react-native-notifications/android/app/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.wix.reactnativenotifications" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:reactnativenotifications] /Users/miraj/assist-versions/Assist/node_modules/react-native-notifications/android/app/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="com.wix.reactnativenotifications" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/miraj/assist-versions/Assist/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/miraj/assist-versions/Assist/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/miraj/assist-versions/Assist/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by johndturn** [comment]
I wonder if #304 would help to fix this, as the error message also mentions `use a compatible library with a minSdk of at most 16`.

I installed the library fresh today and am also running into this same issue.

**Comment by Bilal-Abdeen** [comment]
In (android/build.gradle), I applied the following change. I hope this will NOT break anything. This is my 1st RN project! 
```
- minSdkVersion = 16
+ minSdkVersion = 19
```
