### ISSUE TITLE
[V3.1.0][ANDROID] java.lang.RuntimeException: Cannot convert argument of type class com.wix.reactnativenotifications.fcm.FcmToken

### ISSUE THREAD

**Issue by claudiozam** [wix/react-native-notifications#450]
### **Problem**

Unable to receive a new FCM Push Token on Android.

```
01-18 05:27:01.484  7124  7124 I ReactNativeNotifs: FCM has a new token=cHg2ANzZ2kw:APA91bGpwcoKJlM2fV1_OzQMtIYrDA817rDo7oz1SEIK8VgLM7spPxdcqAi2qegRAgfpjcrTeSAPHnypGGV0OLCnB5n15FIyD5d3aUXuEogSGMpcTyzUi6RuIrNTt23LnlG1b-TbMlpx
01-18 05:27:01.485  7124  7124 D AndroidRuntime: Shutting down VM
01-18 05:27:01.486  7124  7124 E AndroidRuntime: FATAL EXCEPTION: main
01-18 05:27:01.486  7124  7124 E AndroidRuntime: Process: co.handing.mobile, PID: 7124
01-18 05:27:01.486  7124  7124 E AndroidRuntime: java.lang.RuntimeException: Cannot convert argument of type class com.wix.reactnativenotifications.fcm.FcmToken$2
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:181)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.invoke(JavaScriptModuleRegistry.java:91)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at $Proxy7.emit(Unknown Source)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken.sendTokenToJS(FcmToken.java:94)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken$1.onSuccess(FcmToken.java:80)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.wix.reactnativenotifications.fcm.FcmToken$1.onSuccess(FcmToken.java:75)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-18 05:27:01.486  7124  7124 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-18 05:27:01.494  1887  1899 W ActivityManager:   Force finishing activity co.andingqaz.mobile/.MainActivity
```

### **Enviroment**

package.json

```
 "react": "16.9.0"
 "react-native": "0.61.5"
 "react-native-notifications": "^3.1.0"
```

build.gradle

```
'com.google.firebase:firebase-core:17.2.1'
'com.google.firebase:firebase-iid:20.0.2'
'com.google.firebase:firebase-messaging:20.1.0'
```

Thanks

**Comment by claudiozam** [comment]
Fixed on 3.1.1
