### ISSUE TITLE
Crash on android version java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessibl

### ISSUE THREAD

**Issue by taduyde** [wix/react-native-notifications#569]
I have an issue with android app, android app crash when receiving the push notification.
Please help me check:

Process: com.infinityone, PID: 17009
    java.lang.RuntimeException: Unable to instantiate service com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService: java.lang.ClassNotFoundException: Didn't find class "com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService" on path: DexPathList[[zip file "/data/app/com.infinityone-Te57ekemtQSIYlE4EXBpEw==/base.apk"],nativeLibraryDirectories=[/data/app/com.infinityone-Te57ekemtQSIYlE4EXBpEw==/lib/arm64, /data/app/com.infinityone-Te57ekemtQSIYlE4EXBpEw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3529)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService" on path: DexPathList[[zip file "/data/app/com.infinityone-Te57ekemtQSIYlE4EXBpEw==/base.apk"],nativeLibraryDirectories=[/data/app/com.infinityone-Te57ekemtQSIYlE4EXBpEw==/lib/arm64, /data/app/com.infinityone-Te57ekemtQSIYlE4EXBpEw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3526)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 10 more
     Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 13 more
     Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.infinityone-Te57ekemtQSIYlE4EXBpEw==/base.apk:classes3.dex)
        		... 13 more

**Comment by tomahim** [comment]
Having same issue here ? Which versions of firebase-core did you use @taduyde  ? (in android/app gradle ?)

Personally I tried with last version
` implementation 'com.google.firebase:firebase-analytics:17.3.0'`
and 
`implementation 'com.google.firebase:firebase-core:16.0.9'`

None of them worked

**Comment by bobbyrinaldy** [comment]
can someone help this ? i got same isssue here

**Comment by taduyde** [comment]
Hello @tomahim, @bobbyrinaldy, 
I resolved this issue by downgrade the package here: implementation 'com.google.firebase:firebase-core:16.0.0' to 16.0.0

**Comment by Desintegrator** [comment]
same issue

**Comment by priyak-sdei** [comment]
I have solved this by adding/modifying version in build.gradle
 implementation "com.google.firebase:firebase-messaging:20.2.4"
 implementation 'com.google.android.gms:play-services-location:17.0.0'
 implementation "com.google.android.gms:play-services-base:17.4.0"
 implementation "com.google.firebase:firebase-core:17.5.0"
