### ISSUE TITLE
Android crash when start app: java.lang.IncompatibleClassChangeError: Superclass com.google.firebase.iid.zzb of com.google.firebase.messaging.FirebaseMessagingService is declared final 

### ISSUE THREAD

**Issue by taduyde** [wix/react-native-notifications#570]
The issue happened on the android version. 

**Crash detail:**

Process: com.infinityone, PID: 30962
    **java.lang.IncompatibleClassChangeError: Superclass com.google.firebase.iid.zzb of com.google.firebase.messaging.FirebaseMessagingService is declared final** (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.infinityone-X0uRh8zrpGZ8dchOL9fEZA==/base.apk:classes3.dex)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3526)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by reboexpressoapp** [comment]
Really, still there

**Comment by c-lamont** [comment]
Still have this issue too.

**Comment by mvbrazas** [comment]
I have same issue

**Comment by sowmyarsmb** [comment]
Can i have the solution here please ?
