### ISSUE TITLE
App Crashes Upon receiving remote notifications after integrating firebase-crashlytics

### ISSUE THREAD

**Issue by ErangaD** [wix/react-native-notifications#583]
I recently added firebase-crashlytics to my react-native app. Then it crashes after receiving remote notifications. The crashlytics gives the following stack trace.
```
Fatal Exception: java.lang.IncompatibleClassChangeError: com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService
       at dalvik.system.DexFile.defineClassNative(DexFile.java)
       at dalvik.system.DexFile.defineClass(DexFile.java:226)
       at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
       at dalvik.system.DexPathList.findClass(DexPathList.java:321)
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2934)
       at android.app.ActivityThread.access$2000(ActivityThread.java:164)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:159)
       at android.app.ActivityThread.main(ActivityThread.java:5541)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```

Before adding crashlytics dependencies, app received remote notifications fine.

I changed project level and app level gradle files according to the instructions given [here](https://firebase.google.com/docs/crashlytics/get-started-new-sdk?platform=android&authuser=0).
Herer is my **build.gradle (app)** dependencies.
```
{
      .................
      compile project(':react-native-notifications')
      implementation 'com.google.firebase:firebase-core:17.0.0'
      implementation 'com.google.firebase:firebase-analytics:17.3.0'
      implementation 'com.google.firebase:firebase-crashlytics:17.0.0-beta04'
}

```
Earlier **build.gradle (app)** had following dependencies.
```
{
//other dependencies
.................
compile project(':react-native-notifications')
implementation'com.google.firebase:firebase-core:16.0.0' 
}

```
And also I changed `com.google.gms:google-services:4.0.0` to `com.google.gms:google-services:4.3.3` in project level dependencies.

Does anyone have a solution?

**Comment by bobbyrinaldy** [comment]
same problem here, implement push notification always crash when FCM received on android

**Comment by AntoinedeChassey** [comment]
Have you guys found the fix for this ?
