### ISSUE TITLE
Notifications.events().registerRemoteNotificationsRegistered() callback crash

### ISSUE THREAD

**Issue by RosenTomov** [wix/react-native-notifications#624]
Hello, I'm getting crashes/freezes whenever I try to make a http request or write to my db (using Realm) from the Notifications.events().registerRemoteNotificationsRegistered() callback. I'm still getting a token, but I can't do anything with it.

I'm using react-native-navigation with react-native-notifications and noticed that I missed the wiki at the start, about using them together. Is the wiki (Android: working with RNN - https://github.com/wix/react-native-notifications/wiki/Android:-working-with-RNN) still relevant? Most of the links in there are dead.

RN: 0.62.2
Node: 12.16.3
react-native-navigation: 6.7.1
react-native-notifications: 3.2.2

Here's an example error log from logcat

```
2020-06-01 18:35:15.544 547-636/? E/InputDispatcher: channel '9182a4a PopupWindow:58df9e2 (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-06-01 18:35:16.771 29035-29220/com.test E/com.test: Invalid ID 0x00000000.
2020-06-01 18:35:17.940 29035-29183/com.test E/unknown:ReactContextBaseJavaModule: Unhandled SoftException
    java.lang.RuntimeException: Catalyst Instance has already disappeared: requested by WebSocketModule
        at com.facebook.react.bridge.ReactContextBaseJavaModule.getReactApplicationContextIfActiveOrWarn(ReactContextBaseJavaModule.java:67)
        at com.facebook.react.modules.websocket.WebSocketModule.sendEvent(WebSocketModule.java:62)
        at com.facebook.react.modules.websocket.WebSocketModule.access$100(WebSocketModule.java:40)
        at com.facebook.react.modules.websocket.WebSocketModule$1.onMessage(WebSocketModule.java:187)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by tonysbabu** [comment]
Facing the same issue.

**Comment by activebiz** [comment]
Having same issue
