### ISSUE TITLE
Android builds successfully, but app crashes while launching

### ISSUE THREAD

**Issue by leandro-faria** [wix/react-native-notifications#657]
I followed the [installation guide](https://wix.github.io/react-native-notifications/docs/installation-android), faced some problems that I solved with:

`project/build.gradle`
```
ext {
        compileSdkVersion = 28
        targetSdkVersion = 28
        minSdkVersion = 21
        buildToolsVersion = "28.0.2"
        supportLibVersion = "28.0.0"
        androidXCore = "1.0.2"
        kotlinVersion = "1.3.72" // this line
      }
     dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion" // this line
        classpath 'com.google.gms:google-services:4.3.2'
```

`app/build.gradle`
```
    defaultConfig {
...
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative60"
...
```

The other files are just like documentation explains.

My Android app builds successfully, but crashes when the app is opening, with no log in the terminal where metro bundler is running.

Does anyone know what may be happening?

P.S.: I have `react-native-navigation` in my project, but could not follow the links provided in the wiki, since they're broken

**Comment by marudy** [comment]
Use `adb logcat` API to trace the crashing command

**Comment by lukeramsden** [comment]
Also getting this. `adb logcat` shows:

```
08-26 12:34:39.014 17388 17388 W oungwork.mobil: Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
08-26 12:34:39.014 17388 17388 W oungwork.mobil: Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
08-26 12:34:39.032 17388 17388 W System.err: java.lang.ClassNotFoundException: app.youngwork.mobile.MainActivity
08-26 12:34:39.033 17388 17388 W System.err: 	at java.lang.Class.classForName(Native Method)
08-26 12:34:39.034 17388 17388 W System.err: 	at java.lang.Class.forName(Class.java:453)
08-26 12:34:39.034 17388 17388 W System.err: 	at java.lang.Class.forName(Class.java:378)
08-26 12:34:39.035 17388 17388 W System.err: 	at com.zoontek.rnbootsplash.RNBootSplashActivity.getMainActivityClass(RNBootSplashActivity.java:18)
08-26 12:34:39.035 17388 17388 W System.err: 	at com.zoontek.rnbootsplash.RNBootSplashActivity.onCreate(RNBootSplashActivity.java:26)
08-26 12:34:39.035 17388 17388 W System.err: 	at android.app.Activity.performCreate(Activity.java:7148)
08-26 12:34:39.036 17388 17388 W System.err: 	at android.app.Activity.performCreate(Activity.java:7139)
08-26 12:34:39.036 17388 17388 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
08-26 12:34:39.036 17388 17388 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
08-26 12:34:39.037 17388 17388 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
08-26 12:34:39.037 17388 17388 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
08-26 12:34:39.037 17388 17388 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-26 12:34:39.038 17388 17388 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-26 12:34:39.038 17388 17388 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
08-26 12:34:39.038 17388 17388 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-26 12:34:39.038 17388 17388 W System.err: 	at android.os.Looper.loop(Looper.java:193)
08-26 12:34:39.039 17388 17388 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6923)
08-26 12:34:39.039 17388 17388 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-26 12:34:39.039 17388 17388 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-26 12:34:39.039 17388 17388 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
08-26 12:34:39.041 17388 17388 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "app.youngwork.mobile.MainActivity" on path: DexPathList[[zip file "/data/app/app.youngwork.mobile-Es73PTZguNdG1WmoysxchA==/base.apk"],nativeLibraryDirectories=[/data/app/app.youngwork.mobile-Es73PTZguNdG1WmoysxchA==/lib/arm, /data/app/app.youngwork.mobile-Es73PTZguNdG1WmoysxchA==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
08-26 12:34:39.041 17388 17388 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-26 12:34:39.041 17388 17388 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-26 12:34:39.041 17388 17388 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-26 12:34:39.042 17388 17388 W System.err: 	... 20 more
```

Presumably something to do with react-native-bootsplash and react-native-notifications combining?
