### ISSUE TITLE
Getting IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.

### ISSUE THREAD

**Issue by tusharprajapati8888** [wix/react-native-notifications#775]
I'm getting the below crash report in firebase crashlytics (Only Android).

I am not able to reproduce on my device but seems like live users are facing this.

Any help would be highly appreciated.

```
Fatal Exception: java.lang.IllegalStateException: Tried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module.
       at com.facebook.react.bridge.ReactContext.getJSModule(ReactContext.java:148)
       at com.wix.reactnativenotifications.core.JsIOHelper.sendEventToJS(JsIOHelper.java:21)
       at com.wix.reactnativenotifications.core.JsIOHelper.sendEventToJS(JsIOHelper.java:13)
       at com.wix.reactnativenotifications.core.notification.PushNotification.notifyReceivedBackgroundToJS(PushNotification.java:208)
       at com.wix.reactnativenotifications.core.notification.PushNotification.onReceived(PushNotification.java:68)
       at com.wix.reactnativenotifications.fcm.FcmInstanceIdListenerService.onMessageReceived(FcmInstanceIdListenerService.java:28)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(com.google.firebase:firebase-messaging@@21.1.0:13)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(com.google.firebase:firebase-messaging@@21.1.0:8)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(com.google.firebase:firebase-messaging@@21.1.0:3)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(com.google.firebase:firebase-messaging@@21.1.0:3)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(com.google.firebase:firebase-messaging@@21.1.0:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.3.0:6)
       at java.lang.Thread.run(Thread.java:764)
```

![Firebase crash report android](https://user-images.githubusercontent.com/89186578/134164353-95234f9d-c445-4233-9f7f-a450b8a7fd5b.png)

**Comment by moonbe77** [comment]
I'm facing the same issue, It happens if the app receives a notification while is being opened.
How to reproduce, 
Trigger a notification and tap on the app icon just before the notification is received (might need some attempts to get the timing right). 
Found this issue with the same symptoms.
 https://github.com/OneSignal/react-native-onesignal/issues/877

**Comment by aelmadani** [comment]
I've got same error. Did anyone find a solution?

**Comment by dembal1990** [comment]
I downgrade  "expo-notifications" to "0.20.0" version. This is fixed my issue.

**Comment by EnricoMazzu** [comment]
I've found a way to prevent the crash.
Can i reopen a new issue with the PR?

**Comment by levepic** [comment]
> I've found a way to prevent the crash. Can i reopen a new issue with the PR?

Im receiving these errors with my RN 0.74 app since i added vision camera, i suspect the increased loadup time of the app made these crashes happen. Nothing has changed regarding push notifications

**Comment by levepic** [comment]
> I've found a way to prevent the crash. Can i reopen a new issue with the PR?

Could it be released?

**Comment by levepic** [comment]
> I've found a way to prevent the crash. Can i reopen a new issue with the PR?

This should really be released, im getting a lagre number of these errors. It depends on your bundle size so as your app bundle is larger you get more of these errors
