### ISSUE TITLE
[ANDROID] Crash when receiving notification

### ISSUE THREAD

**Issue by billouboq** [wix/react-native-notifications#786]
On react-native 0.66.3 android 11, react-native-notification 4.1.2 when receiving a notification my app crash with this message :

```
11-20 19:59:08.559 24094 24094 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.wix.reactnativenotifications.RNNotificationsPackage: java.lang.InstantiationException: java.lang.Class<com.wix.reactnativenotifications.RNNotificationsPackage> has no zero argument constructor
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4204)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: Caused by: java.lang.InstantiationException: java.lang.Class<com.wix.reactnativenotifications.RNNotificationsPackage> has no zero argument constructor
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
11-20 19:59:08.559 24094 24094 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4183)
```

My config seems to follow the android getting started MainApplication and it builds correctly. I also receive an fcm token so it's not a linking issue, not sure what's going on :/

```
import com.wix.reactnativenotifications.RNNotificationsPackage;

...

packages.add(new RNNotificationsPackage(MainApplication.this));
```

**Comment by billouboq** [comment]
My bad was adding too much things in the AndroidManifest, needed to remove this :


```
<!-- [START firebase_service] -->
<service
		android:name="com.wix.reactnativenotifications.RNNotificationsPackage"
		android:exported="false">
		<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT" />
		</intent-filter>
</service>
<!-- [END firebase_service] -->
```
