### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.netease.huke/com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService (has extras) }: app is in background uid UidRecord{aeba37f u0a323 LAST bg:+5s900ms idle change:cached procs:2 seq(0,0,0)}

### ISSUE THREAD

**Issue by fengmingye** [wix/react-native-notifications#789]
hello, we got the following error:
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.netease.huke/com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService (has extras) }: app is in background uid UidRecord{aeba37f u0a323 LAST bg:+5s900ms idle change:cached procs:2 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1744)
       at android.app.ContextImpl.startService(ContextImpl.java:1699)
       at android.content.ContextWrapper.startService(ContextWrapper.java:669)
       at com.wix.reactnativenotifications.RNNotificationsModule.startFcmIntentService(RNNotificationsModule.java:147)
       at com.wix.reactnativenotifications.RNNotificationsModule.refreshToken(RNNotificationsModule.java:77)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:219)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:929)

Android version: 10,
 "react-native-notifications": "^3.2.2",

**Comment by fengmingye** [comment]
would you help fix this ? thanks
