### ISSUE TITLE
react-native-notifications lib resolved from pods folder even on Android 

### ISSUE THREAD

**Issue by casparss** [wix/react-native-notifications#793]
Whenever I have the pods installed on the project with with react-native-notifications, when developing with Android the Metro Bundler tries to resolve the react-native-notifications library from the Pods folder in ios (and fails)! As soon as i delete pods, the metro bundler seemingly resolves the lib correctly with no errors!

"react-native": "0.64.2"
(not sure what other versions would relevant here?)

Below is the output I'm getting:

```
error: Error: While trying to resolve module `react-native-notifications` from file `/Users/caswork/Projects/mijnkpn-app/packages/data/src/pushNotification/stores/PushNotificationStore.ts`, the package `/Users/caswork/Projects/mijnkpn-app/packages/core/ios/Pods/react-native-notifications/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/caswork/Projects/mijnkpn-app/packages/core/ios/Pods/react-native-notifications/lib/dist/index.js`. Indeed, none of these files exist:

  * /Users/caswork/Projects/mijnkpn-app/packages/core/ios/Pods/react-native-notifications/lib/dist/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.webjs|.native.webjs|.webjs)
  * /Users/caswork/Projects/mijnkpn-app/packages/core/ios/Pods/react-native-notifications/lib/dist/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.webjs|.native.webjs|.webjs)
    at DependencyGraph.resolveDependency (/Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/node-haste/DependencyGraph.js:436:17)
    at Object.resolve (/Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
    at _next (/Users/caswork/Projects/mijnkpn-app/packages/core/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:9)
```

**Comment by see-mik** [comment]
meet the same:
"react-native": "0.65.3",
"react-native-notifications": "^4.3.3",
