### ISSUE TITLE
Android not able to recive app token

### ISSUE THREAD

**Issue by weihangChen** [wix/react-native-notifications#801]
I followed the tutorial and set up for IOS and Android, now everything works on IOS, I can obtain token, notification arrives successfully for foreground/background/quit states. But for Android, nothing works. Device notification access is granted, but I dont see the token being generated. I notice that the documentation is not really up to date when i was setting up for IOS, wondering if there is something missing for Android as well in terms of documentation.

**Comment by weihangChen** [comment]
if I look at the source code, the `FcmInstanceIdListenerService` is not implementing the `onNewToken` method, hence we won't obtain any token
![Screenshot 2022-01-06 at 18 41 32](https://user-images.githubusercontent.com/2369864/148426624-4cbedc4b-09f4-4389-a46a-78a77bce55d5.png)
![Screenshot 2022-01-06 at 18 44 23](https://user-images.githubusercontent.com/2369864/148426952-053859a6-38e0-4d8d-8593-fe2a431a35ea.png)

**Comment by weihangChen** [comment]
following is my code which works fine for iOS not for android


```
Notifications.registerRemoteNotifications();
if (Platform.OS === 'android') {
  Notifications.android.refreshToken();
}

Notifications.events().registerRemoteNotificationsRegistered((event) => {
  console.error(event)
  
  });
});
```

**Comment by weihangChen** [comment]
now I run the app on a device using android studio and debug my app , trace show following , anyone knows how to fix it?
![Screenshot 2022-01-08 at 22 12 56](https://user-images.githubusercontent.com/2369864/148660144-38937046-4f69-46f6-9e16-c330613b81c4.png)

```
2022-01-08 22:07:52.877 12944-12944/com.dialivapp W/ReactNativeNotifs: Fetching FCM registration token failed
    java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR
        at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(com.google.firebase:firebase-messaging@@23.0.0:9)
        at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$3$com-google-firebase-messaging-FirebaseMessaging(com.google.firebase:firebase-messaging@@23.0.0:1)
        at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda10.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR
        at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.1:8)
        at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(com.google.firebase:firebase-messaging@@23.0.0:8)
        at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$3$com-google-firebase-messaging-FirebaseMessaging(com.google.firebase:firebase-messaging@@23.0.0:1) 
        at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda10.run(Unknown Source:4) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.io.IOException: FIS_AUTH_ERROR
        at com.google.firebase.messaging.GmsRpc.handleResponse(com.google.firebase:firebase-messaging@@23.0.0:7)
        at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0$com-google-firebase-messaging-GmsRpc(com.google.firebase:firebase-messaging@@23.0.0:1)
        at com.google.firebase.messaging.GmsRpc$$ExternalSyntheticLambda0.then(Unknown Source:2)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.firebase.messaging.GmsRpc$$ExternalSyntheticLambda1.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.1:8)
        at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.1:5)
        at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.1:3)
        at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.1:1)
        at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:3)
        at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:2)
        at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:14)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8595)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by weihangChen** [comment]
I redownloaded the `google-service.json`, then the authentication starts to work, nothing related to the lib , closing ticket.
