### ISSUE TITLE
build failed when dependency are upgraded to android12

### ISSUE THREAD

**Issue by aftabameen** [wix/react-native-notifications#876]
customer\node_modules\react-native-notifications\lib\android\app\src\main\java\com\wix\reactnativenotifications\core\ReactAppLifecycleFacade.java:50: error: cannot find symbol
        return mReactContext.hasActiveReactInstance();
                            ^
  symbol:   method hasActiveReactInstance()
  location: variable mReactContext of type ReactContext
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-notifications:compileReactNative60DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 43s

    at makeError (E:\repos\customer\node_modules\execa\index.js:174:9)
    at E:\repos\customer\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (E:\repos\customer\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (E:\repos\customer\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

**Comment by aftabameen** [comment]
i have downgraded to version 4.2.0 and it  worked for me.  also I update the Kolten version to 1.5.0
