### ISSUE TITLE
CRITICAL? bug. App crashing

### ISSUE THREAD

**Issue by KingOfTNT** [wix/react-native-notifications#924]
Hi,
When I open my app for the first time it crashes and after I open it again it crashes again after a while.
So I looked in the logs (logcat) and saw `...crashed service com.on_air_project/com.wix.reactnativenotifications`, So I dug deeper and ran the command `adb logcat --buffer=crash `
and it returns
```
12-06 18:52:48.947 11343 11367 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.on_air_project. Make sure to call FirebaseApp.initializeApp(Context) first.
12-06 18:52:48.947 11343 11367 E AndroidRuntime:        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:183)
12-06 18:52:48.947 11343 11367 E AndroidRuntime:        at com.google.firebase.messaging.FirebaseMessaging.getInstance(com.google.firebase:firebase-messaging@@21.1.0:1)
12-06 18:52:48.947 11343 11367 E AndroidRuntime:        at com.wix.reactnativenotifications.fcm.FcmToken.refreshToken(FcmToken.java:75)
12-06 18:52:48.947 11343 11367 E AndroidRuntime:        at com.wix.reactnativenotifications.fcm.FcmToken.onAppReady(FcmToken.java:65)
12-06 18:52:48.947 11343 11367 E AndroidRuntime:        at com.wix.reactnativenotifications.fcm.FcmInstanceIdRefreshHandlerService.onHandleWork(FcmInstanceIdRefreshHandlerService.java:26)
```

What could be the reason? do you need more information?
Please Help!

**Comment by arashkevich25** [comment]
have the same issue, any solution?

**Comment by zhe1ka** [comment]
same
